/**
 * SampleAPI
 * This is a sample API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param name 
 */
data class InlineResponse200 (

    val id: kotlin.Int? = null,
    val name: kotlin.String? = null
) {
}